name: kilted

on:
  pull_request:
    branches:
      - kilted
  push:
    branches:
      - kilted
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: kilted
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: kilted
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          package-name: easynav_common easynav_controller easynav_localizer easynav_maps_manager easynav_planner easynav_sensors easynav_system easynav_support_py easynav_tools
          target-ros2-distro: kilted
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/.github/thirdparty.repos
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          files: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false
